#include "write_mif.h"

#include <chrono>
#include <ctime>
#include <set>
#include <string>

#include "mif_storage_fwd.h"
#include "openfpga_decode.h"
#include "openfpga_digest.h"
#include "openfpga_port.h"
#include "openfpga_version.h"
#include "vtr_log.h"

namespace openfpga {

static void write_mif_file_head(mmostream& os, const bool& include_time_stamp) {
  os << "// " << K_PRELOAD_MEM_TITLE << "\n";
  os << "// Generated by OpenFPGA\n";
  if (include_time_stamp) {
    const auto end = std::chrono::system_clock::now();
    const std::time_t end_time = std::chrono::system_clock::to_time_t(end);
    os << "// Version: " << openfpga::VERSION << "\n";
    os << "// Date: " << std::ctime(&end_time);
  }
}

static void write_mif_segment(const MifStorage& storage,
                              const MifSegmentId& segment_id, mmostream& os) {
  os << "// " << K_PRELOAD_MEM_TITLE << "\n";
  const BasicPort& address_port = storage.addr_range(segment_id);
  if (address_port.is_valid()) {
    os << "// " << address_port.to_verilog_string() << "\n";
  }
  os << "// Data width: " << storage.data_width(segment_id) << "\n";
  os << "// PB_TYPE " << storage.physical_pb(segment_id) << "\n";

  /* $readmemh @addr allows sparse / out-of-order writes; no sort needed. */
  for (const MifMemoryLineId& memory_line_id :
       storage.segment_memory_lines(segment_id)) {
    os << "@" << storage.memory_line_address(memory_line_id) << " "
       << format_hex_word(storage.memory_line_data(memory_line_id),
                          storage.data_width(segment_id))
       << "\n";
  }
}

static void write_mif_to_stream(const MifStorage& storage, mmostream& os,
                                const std::set<std::string>& allowed_ports) {
  bool first = true;
  for (const MifSegmentId& segment_id : storage.segments()) {
    if ((false == allowed_ports.empty()) &&
        (allowed_ports.end() ==
         allowed_ports.find(storage.physical_pb(segment_id)))) {
      continue;
    }
    if (!first) {
      os << "\n";
    }
    first = false;
    write_mif_segment(storage, segment_id, os);
  }
}

int write_mif(const std::string& file_path,
              const MifStorage& aggregated_mif_storage,
              const std::set<std::string>& allowed_ports,
              const bool& include_time_stamp, const bool& verbose) {
  if (aggregated_mif_storage.empty()) {
    VTR_LOG_ERROR("No aggregated MIF data to write\n");
    return CMD_EXEC_FATAL_ERROR;
  }

  size_t num_written = 0;
  for (const MifSegmentId& segment_id : aggregated_mif_storage.segments()) {
    if ((true == allowed_ports.empty()) ||
        (allowed_ports.end() !=
         allowed_ports.find(aggregated_mif_storage.physical_pb(segment_id)))) {
      ++num_written;
    }
  }
  if (0 == num_written) {
    VTR_LOG_ERROR(
      "write_mif: no MIF segment matches the selected circuit model\n");
    return CMD_EXEC_FATAL_ERROR;
  }

  /* mmostream can emit gzip when the path ends with .gz (enabled later). */
  mmostream os(file_path, file_require_gz(file_path));
  check_file_mmostream(file_path.c_str(), os);

  write_mif_file_head(os, include_time_stamp);
  write_mif_to_stream(aggregated_mif_storage, os, allowed_ports);
  if (false == valid_file_mmostream(os)) {
    VTR_LOG_ERROR("I/O error while writing preload .mem file '%s'\n",
                  file_path.c_str());
    return CMD_EXEC_FATAL_ERROR;
  }
  VTR_LOGV(verbose, "write_mif: wrote %zu segment(s) to '%s'\n", num_written,
           file_path.c_str());
  return CMD_EXEC_SUCCESS;
}

} /* namespace openfpga */
