# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
# Configuration file for running experiments
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
# timeout_each_job : FPGA Task script splits fpga flow into multiple jobs
# Each job execute fpga_flow script on combination of architecture & benchmark
# timeout_each_job is timeout for each job
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

[GENERAL]
run_engine=openfpga_shell
power_tech_file = ${PATH:OPENFPGA_PATH}/openfpga_flow/tech/PTM_45nm/45nm.xml
power_analysis = true
spice_output=false
verilog_output=true
timeout_each_job = 20*60
fpga_flow=vpr_blif

[OpenFPGA_SHELL]
openfpga_shell_template=${PATH:OPENFPGA_PATH}/openfpga_flow/openfpga_shell_scripts/custom_rrgraph_generation_example.openfpga
openfpga_arch_file=${PATH:OPENFPGA_PATH}/openfpga_flow/openfpga_arch/k4_frac_N4_40nm_cc_openfpga.xml
openfpga_sim_setting_file=${PATH:OPENFPGA_PATH}/openfpga_flow/openfpga_simulation_settings/fixed_sim_openfpga.xml
openfpga_openfpga_path=${PATH:OPENFPGA_PATH}
openfpga_vpr_device_layout=FPGA44_CUSTOM_GRAPH
openfpga_vpr_route_chan_width=32
openfpga_gsb_dir=${PATH:TASK_DIR}/gsb_xml
openfpga_write_gsb_option=
openfpga_verilog_output_file=./SRC
openfpga_rrgraph_out_file=${PATH:TASK_DIR}/example_custom_rr_graph.xml
# openfpga_independent_bitstream_dir=${PATH:TASK_DIR}/
# openfpga_net_file=${PATH:TASK_DIR}/and2.net.post_routing
# openfpga_place_file=${PATH:TASK_DIR}/and2.place
# openfpga_route_file=${PATH:TASK_DIR}/and2.route
openfpga_write_fabric_hierarchy_option=
openfpga_build_fabric_options=
openfpga_vpr_opts=--sb_maps ${PATH:TASK_DIR}/../SB_MAPS.yml --sb_templates ${PATH:TASK_DIR}/../CRR_CSV --preserve_input_pin_connections off --preserve_output_pin_connections off --annotated_rr_graph off --remove_dangling_nodes off --sb_count_dir sb_count --route_verbosity 3

[ARCHITECTURES]
arch0=${PATH:OPENFPGA_PATH}/openfpga_flow/vpr_arch/k4_frac_N4_tileable_40nm_custrrg.xml

[BENCHMARKS]
bench0=${PATH:OPENFPGA_PATH}/openfpga_flow/benchmarks/micro_benchmark/and2/and2.blif

[SYNTHESIS_PARAM]
bench0_top = and2
bench0_act = ${PATH:OPENFPGA_PATH}/openfpga_flow/benchmarks/micro_benchmark/and2/and2.act
bench0_verilog = ${PATH:OPENFPGA_PATH}/openfpga_flow/benchmarks/micro_benchmark/and2/and2.v

[SCRIPT_PARAM_MIN_ROUTE_CHAN_WIDTH]