FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
ADD .github/workflows/install_dependencies_run.sh install_dependencies_run.sh
RUN bash install_dependencies_test.sh
ADD requirements.txt requirements.txt
RUN python3 -m pip install -r requirements.txt
