/******************************************************************************
 * Member functions for data structure MifLocationMap
 ******************************************************************************/
#include "mif_location_map.h"

#include <chrono>
#include <ctime>
#include <string>

#include "command_exit_codes.h"
#include "openfpga_digest.h"
#include "pugixml.hpp"
#include "pugixml_util.hpp"
#include "vtr_assert.h"
#include "vtr_log.h"
#include "vtr_time.h"

/* begin namespace openfpga */
namespace openfpga {

namespace {

const std::map<t_pl_loc, MifPortSlice> k_empty_phy_locs;

} /* namespace */

const std::map<t_pl_loc, MifPortSlice>& MifLocationMap::phy_locs(
  const std::string& port_name) const {
  auto result = data_port2phy_loc_map_.find(port_name);
  if (result == data_port2phy_loc_map_.end()) {
    return k_empty_phy_locs;
  }
  return result->second;
}

const std::map<std::string, std::map<t_pl_loc, MifPortSlice>>&
MifLocationMap::data_port2phy_loc_map() const {
  return data_port2phy_loc_map_;
}

size_t MifLocationMap::size() const {
  size_t num_locs = 0;
  for (const auto& port_entry : data_port2phy_loc_map_) {
    num_locs += port_entry.second.size();
  }
  return num_locs;
}

bool MifLocationMap::empty() const { return data_port2phy_loc_map_.empty(); }

void MifLocationMap::add(const std::string& port_name, const t_pl_loc& phy_loc,
                         t_pb_graph_node* pb_graph_node,
                         const size_t& data_offset, const size_t& data_width) {
  VTR_ASSERT(nullptr != pb_graph_node);
  MifPortSlice slice;
  slice.pb_graph_node = pb_graph_node;
  slice.data_offset = data_offset;
  slice.data_width = data_width;
  data_port2phy_loc_map_[port_name][phy_loc] = slice;
}

int MifLocationMap::write_to_xml_file(const std::string& fname,
                                      const bool& include_time_stamp,
                                      const bool& verbose) const {
  std::string timer_message =
    std::string("Write fabric MIF location information to an XML file '") +
    fname + std::string("'");

  std::string dir_path = format_dir_path(find_path_dir_name(fname));
  create_directory(dir_path, true, verbose);

  vtr::ScopedStartFinishTimer timer(timer_message);
  VTR_ASSERT(true != fname.empty());

  pugi::xml_document out_xml;

  std::string comment =
    "\n\t- FPGA Fabric MIF Location Information\n\t- Generated by OpenFPGA\n";
  if (include_time_stamp) {
    const auto end = std::chrono::system_clock::now();
    const std::time_t end_time = std::chrono::system_clock::to_time_t(end);
    comment += "\t- Date: ";
    comment += std::ctime(&end_time);
  }
  out_xml.append_child(pugi::node_comment).set_value(comment.c_str());

  pugi::xml_node root_node =
    out_xml.append_child(XML_MIF_COORDINATES_ROOT_NAME);
  for (const auto& port_entry : data_port2phy_loc_map_) {
    for (const auto& loc_entry : port_entry.second) {
      const t_pl_loc& phy_loc = loc_entry.first;
      const MifPortSlice& slice = loc_entry.second;
      VTR_ASSERT(nullptr != slice.pb_graph_node &&
                 nullptr != slice.pb_graph_node->pb_type);

      const std::string pb_type_name =
        slice.pb_graph_node->hierarchical_type_name();
      const std::string x_str = std::to_string(phy_loc.x);
      const std::string y_str = std::to_string(phy_loc.y);
      const std::string z_str = std::to_string(phy_loc.sub_tile);
      const std::string offset_str = std::to_string(slice.data_offset);
      const std::string width_str = std::to_string(slice.data_width);

      pugi::xml_node mif_node =
        root_node.append_child(XML_MIF_LOCATION_NODE_NAME);
      mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_PORT) =
        port_entry.first.c_str();
      mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_PB_TYPE) =
        pb_type_name.c_str();
      mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_DATA_OFFSET) =
        offset_str.c_str();
      mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_DATA_WIDTH) =
        width_str.c_str();
      mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_X) = x_str.c_str();
      mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_Y) = y_str.c_str();
      mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_Z) = z_str.c_str();
    }
  }

  if (!out_xml.save_file(fname.c_str())) {
    VTR_LOG_ERROR("Failed to write MIF location XML file: %s\n", fname.c_str());
    return CMD_EXEC_FATAL_ERROR;
  }

  VTR_LOGV(verbose, "Outputted %lu MIF locations to XML file: %s\n", size(),
           fname.c_str());
  return CMD_EXEC_SUCCESS;
}

} /* end namespace openfpga */
