/******************************************************************************
 * Member functions for data structure MifLocationMap
 ******************************************************************************/
#include "mif_location_map.h"

#include <chrono>
#include <ctime>
#include <fstream>

#include "openfpga_digest.h"
#include "vtr_assert.h"
#include "vtr_log.h"
#include "vtr_time.h"

/* begin namespace openfpga */
namespace openfpga {

size_t MifLocationMap::find_mif_location_index(
  const size_t& x, const size_t& y, const size_t& z,
  const std::string& pb_type_path) const {
  std::array<size_t, 3> coord = {x, y, z};
  auto result = mif_coord_lookup_.find(coord);
  if (result == mif_coord_lookup_.end()) {
    return size_t(-1);
  }
  for (const size_t& loc_id : result->second) {
    VTR_ASSERT(loc_id < mif_locations_.size());
    if (mif_locations_[loc_id].pb_type_path == pb_type_path) {
      return loc_id;
    }
  }
  return size_t(-1);
}

bool MifLocationMap::has_mif_location(const size_t& x, const size_t& y,
                                      const size_t& z,
                                      const std::string& pb_type_path) const {
  return size_t(-1) != find_mif_location_index(x, y, z, pb_type_path);
}

const MifLocation& MifLocationMap::mif_location(
  const size_t& x, const size_t& y, const size_t& z,
  const std::string& pb_type_path) const {
  const size_t loc_id = find_mif_location_index(x, y, z, pb_type_path);
  VTR_ASSERT(size_t(-1) != loc_id);
  return mif_locations_[loc_id];
}

size_t MifLocationMap::data_offset(const size_t& x, const size_t& y,
                                   const size_t& z,
                                   const std::string& pb_type_path) const {
  if (false == has_mif_location(x, y, z, pb_type_path)) {
    return size_t(-1);
  }
  return mif_location(x, y, z, pb_type_path).data_offset;
}

size_t MifLocationMap::data_width(const size_t& x, const size_t& y,
                                  const size_t& z,
                                  const std::string& pb_type_path) const {
  if (false == has_mif_location(x, y, z, pb_type_path)) {
    return size_t(-1);
  }
  return mif_location(x, y, z, pb_type_path).data_width;
}

std::string MifLocationMap::port_name(const size_t& x, const size_t& y,
                                      const size_t& z,
                                      const std::string& pb_type_path) const {
  if (false == has_mif_location(x, y, z, pb_type_path)) {
    return std::string();
  }
  return mif_location(x, y, z, pb_type_path).port_name;
}

const std::vector<MifLocation>& MifLocationMap::mif_locations() const {
  return mif_locations_;
}

bool MifLocationMap::empty() const { return mif_locations_.empty(); }

void MifLocationMap::set_mif_location(const size_t& x, const size_t& y,
                                      const size_t& z,
                                      const std::string& pb_type_path,
                                      const std::string& port_name,
                                      const size_t& data_offset,
                                      const size_t& data_width) {
  if (true == has_mif_location(x, y, z, pb_type_path)) {
    VTR_LOG_WARN(
      "Attempt to add duplicated MIF location for pb_type '%s' at "
      "(%lu, %lu, %lu)! Skip to save memory\n",
      pb_type_path.c_str(), x, y, z);
    return;
  }

  MifLocation loc;
  loc.x = x;
  loc.y = y;
  loc.z = z;
  loc.pb_type_path = pb_type_path;
  loc.port_name = port_name;
  loc.data_offset = data_offset;
  loc.data_width = data_width;

  const size_t loc_id = mif_locations_.size();
  mif_locations_.push_back(loc);
  mif_coord_lookup_[{x, y, z}].push_back(loc_id);
}

int MifLocationMap::write_to_xml_file(const std::string& fname,
                                      const bool& include_time_stamp,
                                      const bool& verbose) const {
  std::string timer_message =
    std::string("Write fabric MIF location information to an XML file '") +
    fname + std::string("'");

  std::string dir_path = format_dir_path(find_path_dir_name(fname));
  create_directory(dir_path, true, verbose);

  vtr::ScopedStartFinishTimer timer(timer_message);
  VTR_ASSERT(true != fname.empty());

  std::fstream fp;
  fp.open(fname, std::fstream::out | std::fstream::trunc);
  check_file_stream(fname.c_str(), fp);

  fp << "<!--" << std::endl;
  fp << "\t- FPGA Fabric MIF Location Information" << std::endl;
  fp << "\t- Generated by OpenFPGA" << std::endl;
  if (include_time_stamp) {
    auto end = std::chrono::system_clock::now();
    std::time_t end_time = std::chrono::system_clock::to_time_t(end);
    fp << "\t- Date: " << std::ctime(&end_time);
  }
  fp << "-->" << std::endl;
  fp << std::endl;
  fp << "<mif_coordinates>\n";

  for (const MifLocation& loc : mif_locations_) {
    fp << "\t"
       << "<mif pb_type=\"" << loc.pb_type_path << "\"";
    fp << " port=\"" << loc.port_name << "\"";
    fp << " data_offset=\"" << loc.data_offset << "\"";
    fp << " data_width=\"" << loc.data_width << "\"";
    fp << " x=\"" << loc.x << "\"";
    fp << " y=\"" << loc.y << "\"";
    fp << " z=\"" << loc.z << "\"";
    fp << "/>\n";
  }
  fp << "</mif_coordinates>\n";
  fp.close();

  VTR_LOGV(verbose, "Outputted %lu MIF locations to XML file: %s\n",
           mif_locations_.size(), fname.c_str());
  return 0;
}

bool MifLocationMap::is_valid_coord(const int& x, const int& y,
                                    const int& z) const {
  return (0 <= x) && (0 <= y) && (0 <= z);
}

} /* end namespace openfpga */
