/******************************************************************************
 * Member functions for data structure MifLocationMap
 ******************************************************************************/
#include "mif_location_map.h"

#include <chrono>
#include <ctime>
#include <string>

#include "command_exit_codes.h"
#include "openfpga_digest.h"
#include "pugixml.hpp"
#include "pugixml_util.hpp"
#include "vtr_assert.h"
#include "vtr_log.h"
#include "vtr_time.h"

/* begin namespace openfpga */
namespace openfpga {

size_t MifLocationMap::find_mif_location_index(
  const size_t& x, const size_t& y, const size_t& z,
  const std::string& pb_type_path) const {
  std::array<size_t, 3> coord = {x, y, z};
  auto result = mif_coord_lookup_.find(coord);
  if (result == mif_coord_lookup_.end()) {
    return size_t(-1);
  }
  for (const size_t& loc_id : result->second) {
    VTR_ASSERT(loc_id < mif_locations_.size());
    if (mif_locations_[loc_id].pb_type_path == pb_type_path) {
      return loc_id;
    }
  }
  return size_t(-1);
}

bool MifLocationMap::has_mif_location(const size_t& x, const size_t& y,
                                      const size_t& z,
                                      const std::string& pb_type_path) const {
  return size_t(-1) != find_mif_location_index(x, y, z, pb_type_path);
}

const MifLocation& MifLocationMap::mif_location(
  const size_t& x, const size_t& y, const size_t& z,
  const std::string& pb_type_path) const {
  const size_t loc_id = find_mif_location_index(x, y, z, pb_type_path);
  VTR_ASSERT(size_t(-1) != loc_id);
  return mif_locations_[loc_id];
}

size_t MifLocationMap::data_offset(const size_t& x, const size_t& y,
                                   const size_t& z,
                                   const std::string& pb_type_path) const {
  if (false == has_mif_location(x, y, z, pb_type_path)) {
    return size_t(-1);
  }
  return mif_location(x, y, z, pb_type_path).data_offset;
}

size_t MifLocationMap::data_width(const size_t& x, const size_t& y,
                                  const size_t& z,
                                  const std::string& pb_type_path) const {
  if (false == has_mif_location(x, y, z, pb_type_path)) {
    return size_t(-1);
  }
  return mif_location(x, y, z, pb_type_path).data_width;
}

std::string MifLocationMap::port_name(const size_t& x, const size_t& y,
                                      const size_t& z,
                                      const std::string& pb_type_path) const {
  if (false == has_mif_location(x, y, z, pb_type_path)) {
    return std::string();
  }
  return mif_location(x, y, z, pb_type_path).port_name;
}

const std::vector<MifLocation>& MifLocationMap::mif_locations() const {
  return mif_locations_;
}

bool MifLocationMap::empty() const { return mif_locations_.empty(); }

void MifLocationMap::set_mif_location(const size_t& x, const size_t& y,
                                      const size_t& z,
                                      const std::string& pb_type_path,
                                      const std::string& port_name,
                                      const size_t& data_offset,
                                      const size_t& data_width) {
  if (true == has_mif_location(x, y, z, pb_type_path)) {
    VTR_LOG_WARN(
      "Attempt to add duplicated MIF location for pb_type '%s' at "
      "(%lu, %lu, %lu)! Skip to save memory\n",
      pb_type_path.c_str(), x, y, z);
    return;
  }

  MifLocation loc;
  loc.x = x;
  loc.y = y;
  loc.z = z;
  loc.pb_type_path = pb_type_path;
  loc.port_name = port_name;
  loc.data_offset = data_offset;
  loc.data_width = data_width;

  const size_t loc_id = mif_locations_.size();
  mif_locations_.push_back(loc);
  mif_coord_lookup_[{x, y, z}].push_back(loc_id);
}

int MifLocationMap::write_to_xml_file(const std::string& fname,
                                      const bool& include_time_stamp,
                                      const bool& verbose) const {
  std::string timer_message =
    std::string("Write fabric MIF location information to an XML file '") +
    fname + std::string("'");

  std::string dir_path = format_dir_path(find_path_dir_name(fname));
  create_directory(dir_path, true, verbose);

  vtr::ScopedStartFinishTimer timer(timer_message);
  VTR_ASSERT(true != fname.empty());

  pugi::xml_document out_xml;

  std::string comment =
    "\n\t- FPGA Fabric MIF Location Information\n\t- Generated by OpenFPGA\n";
  if (include_time_stamp) {
    const auto end = std::chrono::system_clock::now();
    const std::time_t end_time = std::chrono::system_clock::to_time_t(end);
    comment += "\t- Date: ";
    comment += std::ctime(&end_time);
  }
  out_xml.append_child(pugi::node_comment).set_value(comment.c_str());

  pugi::xml_node root_node =
    out_xml.append_child(XML_MIF_COORDINATES_ROOT_NAME);
  for (const MifLocation& loc : mif_locations_) {
    pugi::xml_node mif_node =
      root_node.append_child(XML_MIF_LOCATION_NODE_NAME);
    mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_PB_TYPE) =
      loc.pb_type_path.c_str();
    mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_PORT) =
      loc.port_name.c_str();
    mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_DATA_OFFSET) =
      std::to_string(loc.data_offset).c_str();
    mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_DATA_WIDTH) =
      std::to_string(loc.data_width).c_str();
    mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_X) =
      std::to_string(loc.x).c_str();
    mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_Y) =
      std::to_string(loc.y).c_str();
    mif_node.append_attribute(XML_MIF_LOCATION_ATTRIBUTE_Z) =
      std::to_string(loc.z).c_str();
  }

  if (!out_xml.save_file(fname.c_str())) {
    VTR_LOG_ERROR("Failed to write MIF location XML file: %s\n", fname.c_str());
    return CMD_EXEC_FATAL_ERROR;
  }

  VTR_LOGV(verbose, "Outputted %lu MIF locations to XML file: %s\n",
           mif_locations_.size(), fname.c_str());
  return CMD_EXEC_SUCCESS;
}

} /* end namespace openfpga */
