/*********************************************************************
 * This function writes the RR_graph generated by VPR into a file in XML format
 * Information included in the file includes rr nodes, rr switches, 
 * the grid, block info, node indices
 ********************************************************************/

#ifndef WRITE_XML_RR_GRAPH_OBJ_H
#define WRITE_XML_RR_GRAPH_OBJ_H

void write_xml_rr_graph_obj(const char *file_name, const RRGraph& rr_graph);

#endif
