#!/usr/bin/env bash

sudo apt-get update

sudo apt-get install -y \
    autoconf \
    automake \
    bison \
    ccache \
    cmake \
    ctags \
    curl \
    doxygen \
    flex \
    fontconfig \
    gdb \
    git \
    gperf \
    iverilog \
    libc6-dev \
    libcairo2-dev \
    libevent-dev \
    libffi-dev \
    libfontconfig1-dev \
    liblist-moreutils-perl \
    libncurses5-dev \
    libreadline-dev \
    libx11-dev \
    libxft-dev \
    libxml++2.6-dev \
    make \
    perl \
    pkg-config \
    python3 \
    python3-setuptools \
    python3-lxml \
    python3-pip \
    qt5-default \
    tcllib \
    tcl8.6-dev \
    texinfo \
    time \
    valgrind \
    wget \
    zip \
    swig \
    expect \
    g++-6 \ 
    gcc-6 \ 
    g++-7 \ 
    gcc-7 \ 
    g++-8 \ 
    gcc-8 \ 
    g++-9 \ 
    gcc-9 \ 
    g++-10 \ 
    gcc-10 \ 
    g++-11 \ 
    gcc-11 \ 
    clang-6.0 \ 
    clang-7 \ 
    clang-10
